// Ported verbatim from the web app's lib/mamajanMenu.ts - plain data, no web APIs.
// frontend/ stays the source of truth for this file; re-copy it when the menu changes.
// Full Mamajan menu, sourced from the restaurant's own digital menu
// (kiosk02.robotpos.com/crea/mamajan/qr/1). Prices in AZN (₼).

export interface MenuItem {
  id: string
  name: string
  price: number
  description?: string
  image?: string
}

export interface MenuCategory {
  id: string
  name: string
  group: "food" | "bar"
  items: MenuItem[]
}

type Row = [string, number, string?, string?]

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[əğıöşüç]/g, (c) => ({ ə: "e", ğ: "g", ı: "i", ö: "o", ş: "s", ü: "u", ç: "c" })[c] ?? c)
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
}

function cat(name: string, group: "food" | "bar", rows: Row[]): MenuCategory {
  const catId = slugify(name)
  return {
    id: catId,
    name,
    group,
    items: rows.map(([n, price, description, image], i) => ({
      id: `${catId}-${i}-${slugify(n)}`,
      name: n,
      price,
      description,
      image,
    })),
  }
}

export const mamajanMenu: MenuCategory[] = [
  cat("Şorbalar", "food", [
    ["Xarço", 9, "Tomat, günəbaxan yağı, pul bibər, Uçxo Suneli, Xarço Suneli, göyərti, düyü, ət, soğan", "/menu/mamajan/sorbalar/0.avif"],
    ["Toyuq Şorbası", 8, "Toyuq filesi, soğan, düyü, kartof, kök, rəngli bibər, göyərti", "/menu/mamajan/sorbalar/1.avif"],
    ["Düşbərə Şorbası", 8, "Düşbərə xəmiri, ət, bulyon, göyərti, nanə qurusu, üzüm sirkəsi", "/menu/mamajan/sorbalar/2.avif"],
    ["Göbələk Şorbası", 7, "Göbələk, soğan, düyü, kartof, rəngli bibər, göyərti", "/menu/mamajan/sorbalar/3.jpg"],
  ]),
  cat("Salatlar", "food", [
    ["Pomidor Salatı Zoğal Sousunda", 9, "Pomidor, qırmızı soğan, göyərti, ağ küncüt, zoğal əzməsi", "/menu/mamajan/salatlar/0.avif"],
    ["Papajan Salatı", 15, "Kahı, pomidor, xiyar, qoz ləpəsi, yaşıl tkemali, zeytun yağı, lobya, can əti", "/menu/mamajan/salatlar/1.avif"],
    ["Manqal Salatı", 8, "Badımcan, rəngli bibər, qırmızı soğan, pomidor, göyərti", "/menu/mamajan/salatlar/2.avif"],
    ["Gürcü Salatı", 9, "Xiyar, pomidor, rəngli bibər, göyərti, zeytun yağı, üzüm sirkəsi, qoz ləpəsi", "/menu/mamajan/salatlar/3.avif"],
    ["Mamajan Salatı", 16, "Toyuq filesi, aysberq kahısı, gül kələmi, brokoli, araxis, qoz ləpəsi, soya sousu, bal", "/menu/mamajan/salatlar/4.avif"],
    ["Mamajan Badımcan Salatı", 11],
    ["Mamajan Badımcan Salatı (Böyük)", 14],
    ["Sezar Salatı", 9, "Toyuq filesi, aysberq kahısı, suxarik, pomidor, Parmezan pendiri, Sezar sousu", "/menu/mamajan/salatlar/7.avif"],
    ["Gürcüsayağı Toyuq Salatı", 9, "Toyuq filesi, soğan, göyərti, şüyüd, şirin bibər, mayonez, xiyar turşusu", "/menu/mamajan/salatlar/8.avif"],
    ["Acılı Ət Salatı", 12, "Sarımsaq, ət, rəngli bibər, göyərti, qoz ləpəsi, zeytun yağı, pul bibər", "/menu/mamajan/salatlar/9.avif"],
    ["Çoban Salatı", 8, "Xiyar, pomidor, qırmızı soğan, zeytun yağı, göyərti, limon suyu", "/menu/mamajan/salatlar/10.avif"],
    ["Olivye Salatı", 9, "Kartof, kök, yumurta, yaşıl noxud, göyərti, xiyar, mayonez", "/menu/mamajan/salatlar/11.avif"],
    ["Dil Salatı", 11, "Dil, rəngli bibər, xiyar, göyərti, mayonez", "/menu/mamajan/salatlar/12.avif"],
  ]),
  cat("Soyuq Qəlyanaltılar", "food", [
    ["Soyuq Qəlyanaltı Seti", 35, "Ajabsandali, badımcan ruleti, pxali, suluquni, naduqi, qozlu lobya, gürcüsayağı basdırma, dil", "/menu/mamajan/soyuq-qelyanaltilar/0.avif"],
    ["Ajabsandali", 9, "Badımcan, qırmızı soğan, kök, rəngli bibər, zeytun yağı", "/menu/mamajan/soyuq-qelyanaltilar/1.avif"],
    ["Tərəvəz Buketi", 8, "Xiyar, pomidor, göyərti", "/menu/mamajan/soyuq-qelyanaltilar/2.avif"],
    ["Pxali Assorti", 9, "Kök, qoz ləpəsi, göyərti, sarımsaq, çuğundur, ıspanaq", "/menu/mamajan/soyuq-qelyanaltilar/3.avif"],
    ["Turşu Assorti", 9, "Xiyar, pomidor, ağ və qırmızı turşular, acı bibər turşusu, alça turşusu", "/menu/mamajan/soyuq-qelyanaltilar/4.avif"],
    ["Ət Assorti", 20, "Hisə verilmiş toyuq filesi, mal əti, hinduşka əti, ət basdırma", "/menu/mamajan/soyuq-qelyanaltilar/5.avif"],
    ["Suluquni", 8, "Suluquni pendiri", "/menu/mamajan/soyuq-qelyanaltilar/6.avif"],
    ["Naduqi", 8, "Süzmə, nanə qurusu, pirpita pendiri", "/menu/mamajan/soyuq-qelyanaltilar/7.avif"],
    ["Saçivi", 11, "Qoz ləpəsi, toyuq filesi, bulyon", "/menu/mamajan/soyuq-qelyanaltilar/8.avif"],
    ["Mamajan Badımcan Ruleti", 9, "Qoz ləpəsi, sarımsaq, göyərti, badımcan", "/menu/mamajan/soyuq-qelyanaltilar/9.avif"],
    ["Qozlu Lobya", 9, "Qırmızı lobya, qoz ləpəsi, göyərti", "/menu/mamajan/soyuq-qelyanaltilar/10.avif"],
    ["Zeytun", 7, "Qara və yaşıl zeytun", "/menu/mamajan/soyuq-qelyanaltilar/11.avif"],
    ["Süzmə", 6, undefined, "/menu/mamajan/soyuq-qelyanaltilar/12.avif"],
    ["Gürcü Rollu Baje Sousunda", 10, "Naduqi, suluquni, xiyar, pomidor, kahı", "/menu/mamajan/soyuq-qelyanaltilar/13.avif"],
    ["Pendir Assorti", 14, "Ağ pendir, şüyüdlü pendir, kopiçeni, suluquni, saçaq pendiri, süzmə", "/menu/mamajan/soyuq-qelyanaltilar/14.avif"],
    ["Səhər Yeməyi 2 Nəfər", 28, "Pendir, mürəbbə, zeytun, qaymaq, sosiska, yumurta, çörək, çay, limitsiz", "/menu/mamajan/soyuq-qelyanaltilar/15.jpg"],
    ["Səhər Yeməyi 4 Nəfər", 52, "Pendir, mürəbbə, zeytun, qaymaq, sosiska, yumurta, çörək, çay, limitsiz", "/menu/mamajan/soyuq-qelyanaltilar/16.jpg"],
  ]),
  cat("Ət Yeməkləri", "food", [
    ["Ocaxuri Acar", 20, "Xaçapuri xəmiri, mal əti, kartof, rəngli bibər, ağ soğan, göyərti, sarımsaq", "/menu/mamajan/et-yemekleri/0.avif"],
    ["Tibilisuri", 16, "Kartof, kök, yumurta, ət, Mozarella pendiri, mayonez, pomidor", "/menu/mamajan/et-yemekleri/1.avif"],
    ["Abxazuri", 14, "Ət, Mozarella pendiri, qaymaq, smetan", "/menu/mamajan/et-yemekleri/2.avif"],
    ["Çaxapuli", 17, "Quzu əti, alça, tərxun, kişniş, şüyüd", "/menu/mamajan/et-yemekleri/3.avif"],
    ["Arabuli", 17, "Kondari, göyərti, qiymə, pul bibər, pomidor, mayonez, Mozarella pendiri", "/menu/mamajan/et-yemekleri/4.avif"],
    ["Kupati", 14, "Quzu əti, mal əti, ağ soğan, rəngli bibər, göyərti, Kondari, nar", "/menu/mamajan/et-yemekleri/5.avif"],
    ["Albalı Sousunda Can Əti", 19, "Can əti, şabalıd, ağ soğan, albalı", "/menu/mamajan/et-yemekleri/6.avif"],
    ["Gürcü Solyanka", 14, "Ət, tomat, ağ soğan, göyərti, Ximeri Kinza, Uçxo Suneli", "/menu/mamajan/et-yemekleri/7.avif"],
    ["Ocaxuri (Ət ilə)", 16, "Ət, kartof, rəngli bibər, ağ soğan, göyərti, sarımsaq", "/menu/mamajan/et-yemekleri/8.avif"],
    ["Ocaxuri (Donuz Əti ilə)", 12, "Donuz əti, kartof, şirin bibər, rəngli bibər, ağ soğan, göyərti, sarımsaq", "/menu/mamajan/et-yemekleri/9.avif"],
    ["Acikalı Quzu Qabırğası", 19, "Quzu antrikot, tomat, sarımsaq, göyərti, acika", "/menu/mamajan/et-yemekleri/10.avif"],
    ["Südlü Suluqunidə Şampinyon", 12, "Göbələk şampinyon, suluquni pendiri", "/menu/mamajan/et-yemekleri/11.avif"],
    ["Sobada Suluquni", 12, "Suluquni pendiri", "/menu/mamajan/et-yemekleri/12.avif"],
    ["Saxsı Qabda Lobya", 10, "Özbək lobyası, göyərti, Kondari, Uçxo Suneli, çəkilmiş qoz", "/menu/mamajan/et-yemekleri/13.avif"],
    ["Çaşuşuli (Mal əti)", 14, "Ət, tomat, ağ soğan, göyərti, Ximeri Kinza, Uçxo Suneli", "/menu/mamajan/et-yemekleri/14.avif"],
    ["Şefin Yeməyi", 20, "Mozarella pendiri, göbələk şampinyon, smetan, qaymaq, toyuq filesi", "/menu/mamajan/et-yemekleri/15.avif"],
    ["Ocaxuri (Göbələk ilə)", 11, "Göbələk şampinyon, kartof, rəngli bibər, ağ soğan, göyərti, sarımsaq", "/menu/mamajan/et-yemekleri/16.avif"],
    ["Krevetka Çkmeruli Sousunda", 18, undefined, "/menu/mamajan/et-yemekleri/17.avif"],
    ["Xaça Burger", 14, "Xaçapuri xəmiri, ağ pendir, Mozarella pendiri, ət, pomidor, duzlu xiyar, kahı", "/menu/mamajan/et-yemekleri/18.avif"],
  ]),
  cat("Toyuq Yeməkləri", "food", [
    ["Mamajan Burger", 12, "Xaçapuri xəmiri, ağ pendir, Mozarella pendiri, toyuq filesi, pomidor, duzlu xiyar, kahı", "/menu/mamajan/toyuq-yemekleri/0.avif"],
    ["Çolpa Tkemali Sousunda", 18, "Çolpa, yaşıl tkemali", "/menu/mamajan/toyuq-yemekleri/1.jpg"],
    ["Çaxoxbili", 14, "Çolpa, ağ soğan, pomidor, yumurta", "/menu/mamajan/toyuq-yemekleri/2.avif"],
    ["Gürcüsayağı Tabaka", 16, "Çolpa", "/menu/mamajan/toyuq-yemekleri/3.avif"],
    ["Kupati (Toyuq)", 12, "Toyuq filesi, ağ soğan, rəngli bibər, göyərti, Kondari, nar", "/menu/mamajan/toyuq-yemekleri/4.avif"],
    ["Çkmeruli", 17, "Çolpa, mayonez, bulyon, sarımsaq, pul bibər", "/menu/mamajan/toyuq-yemekleri/5.avif"],
    ["Ocaxuri (Toyuq)", 12, "Toyuq filesi, kartof, rəngli bibər, ağ soğan, göyərti, sarımsaq", "/menu/mamajan/toyuq-yemekleri/6.avif"],
    ["Kuçmaçi", 12, "Toyuq içalatı, ağ soğan, nar, sarımsaq, Kondari", "/menu/mamajan/toyuq-yemekleri/7.avif"],
    ["Toyuq Langet", 9, "Toyuq filesi, kartof fri, ketçup", "/menu/mamajan/toyuq-yemekleri/8.avif"],
    ["Naggets", 8, "Toyuq filesi, kartof fri, yumurta, ketçup", "/menu/mamajan/toyuq-yemekleri/9.avif"],
    ["Sulugunidə Bişmiş Gürcüsayağı Toyuq", 18, "Çolpa, mozarella pendiri", "/menu/mamajan/toyuq-yemekleri/10.avif"],
  ]),
  cat("Balıq Yeməkləri", "food", [
    ["Sudak Tava", 17, "Sudak balığı", "/menu/mamajan/baliq-yemekleri/0.avif"],
    ["Sudak Manqalda", 17, "Sudak balığı", "/menu/mamajan/baliq-yemekleri/1.png"],
    ["Tavada Dorado", 15, "Dorado balığı", "/menu/mamajan/baliq-yemekleri/2.avif"],
    ["Hisə Verilmiş Dorado", 15, "Dorado balığı, 400-600 qram", "/menu/mamajan/baliq-yemekleri/3.avif"],
    ["Forel Tava", 14, "400-600 qram", "/menu/mamajan/baliq-yemekleri/4.avif"],
    ["Forel Manqal", 14, "400-600 qram", "/menu/mamajan/baliq-yemekleri/5.avif"],
    ["Zoğal Sousunda Forel", 15, "Forel balığı, zoğal sousu, limon"],
    ["Beluqa Manqal", 28],
    ["Syomqa Tava", 20, undefined, "/menu/mamajan/baliq-yemekleri/8.avif"],
    ["Syomqa Manqal", 20, undefined, "/menu/mamajan/baliq-yemekleri/9.avif"],
    ["Zoğal Sousunda Forel (Manqal)", 15, "Forel balığı, zoğal, limon", "/menu/mamajan/baliq-yemekleri/10.avif"],
  ]),
  cat("Qarnirlər", "food", [
    ["Evsayağı Kartof", 6, "Kartof, soğan, günəbaxan yağı", "/menu/mamajan/qarnirler/0.avif"],
    ["Kartof Fri", 5, "Kartof, ketçup", "/menu/mamajan/qarnirler/1.avif"],
    ["Meksikasayağı Kartof", 6, "Kartof, ketçup, mayonez, pul bibər, sarımsaq, oreqano", "/menu/mamajan/qarnirler/2.avif"],
    ["Düyü", 5, "Düyü, limon, qara zeytun", "/menu/mamajan/qarnirler/3.avif"],
  ]),
  cat("Kabablar", "food", [
    ["Çörəkdə Bişmiş Assorti Kabab 2 nəfər", 32],
    ["Çörəkdə Bişmiş Assorti Kabab 4 nəfər", 45],
    ["Lülə", 10, "Ağ və qırmızı soğan, quzu quyruğu, quzu əti", "/menu/mamajan/kabablar/2.avif"],
    ["Gürcüsayağı Lülə (Donuz Əti)", 10, undefined, "/menu/mamajan/kabablar/3.avif"],
    ["Toyuq Lülə", 8, "Qırmızı soğan, ağ soğan, quzu quyruğu, toyuq", "/menu/mamajan/kabablar/4.avif"],
    ["Tikə Kabab", 10, "Ağ və qırmızı soğan, quzu əti", "/menu/mamajan/kabablar/5.avif"],
    ["Antrikot", 11, "250 qram", "/menu/mamajan/kabablar/6.avif"],
    ["Toyuq Kababı", 8, "Toyuq əti, qırmızı soğan, tomat", "/menu/mamajan/kabablar/7.avif"],
    ["Qanad Kabab", 7, "Toyuq qanadları", "/menu/mamajan/kabablar/8.avif"],
    ["Bastırma Kabab", 13, "Kəklikotu, limon, ağ və qırmızı soğan, ət", "/menu/mamajan/kabablar/9.avif"],
    ["Donuz Eskolop", 16, "Donuz qabırğası, ağ və qırmızı soğan", "/menu/mamajan/kabablar/10.avif"],
    ["Donuz Kababı", 10, "Donuz əti, ağ və qırmızı soğan", "/menu/mamajan/kabablar/11.avif"],
    ["Tərəvəz Kababı", 4, "Pomidor, badımcan, rəngli bibər", "/menu/mamajan/kabablar/12.avif"],
    ["Quyruqlu Kartof Kababı", 8, "Kartof, quzu quyruğu", "/menu/mamajan/kabablar/13.avif"],
    ["Semeçka Kababı", 8, "Quzu antrikot, ağ və qırmızı soğan", "/menu/mamajan/kabablar/14.avif"],
    ["Dana Dili Kababı", 9, "Dil, ağ və qırmızı soğan", "/menu/mamajan/kabablar/15.avif"],
    ["Mamajan Kababı", 12, "Kəklikotu, limon, mal əti, quzu quyruğu, rəngli bibər", "/menu/mamajan/kabablar/16.avif"],
    ["Şaurma Kababı", 11, "Toyuq lüləsi, lavaş, pomidor, xiyar turşusu, qırmızı soğan, aysberq kahısı", "/menu/mamajan/kabablar/17.avif"],
    ["Hinduşka Kababı", 11],
  ]),
  cat("Xəmir Yeməkləri", "food", [
    ["Gürcü Qutabı", 6, "Qiymə, xaçapuri xəmiri, göyərti, limon", "/menu/mamajan/xemir-yemekleri/0.avif"],
    ["Çeburek", 6, "Xəmir, qiymə", "/menu/mamajan/xemir-yemekleri/1.avif"],
    ["Xəngəl (Ət)", 1.6, "Mal əti, soğan, cirə, göyərti", "/menu/mamajan/xemir-yemekleri/2.avif"],
    ["Xəngəl (Göbələk)", 2, "Göbələk, cirə, istiot, göyərti", "/menu/mamajan/xemir-yemekleri/3.avif"],
    ["Xəngəl (Suluquni)", 2, "Xəmir, suluquni", "/menu/mamajan/xemir-yemekleri/4.avif"],
    ["Qızardılmış Xəngəl", 2, "Mal əti, soğan, cirə, göyərti", "/menu/mamajan/xemir-yemekleri/5.avif"],
    ["Xaçapuri Meqrel", 14, "Xaçapuri xəmiri, ağ pendir, mozarella pendiri", "/menu/mamajan/xemir-yemekleri/6.avif"],
    ["Xaçapuri İmereti", 15, "Xaçapuri xəmiri, ağ pendir, mozarella pendiri, kərə yağı", "/menu/mamajan/xemir-yemekleri/7.avif"],
    ["Xaçapuri Acar", 14, "Xaçapuri xəmiri, ağ pendir, mozarella pendiri, kərə yağı, yumurta", "/menu/mamajan/xemir-yemekleri/8.avif"],
    ["Xaçapuri Qatqat", 15, "Qat-qat xəmiri, ağ pendir", "/menu/mamajan/xemir-yemekleri/9.avif"],
    ["Şişdə Xaçapuri", 16, "Xaçapuri xəmiri, mozarella pendiri, ağ və qara küncüt", "/menu/mamajan/xemir-yemekleri/10.avif"],
    ["Xaçapuri Lobiani", 13, "Xaçapuri xəmiri, Özbək lobyası, göy pomidor turşusu", "/menu/mamajan/xemir-yemekleri/11.avif"],
    ["Xaçapuri Mamajan", 17, "Xaçapuri xəmiri, ət, tomat, ağ pendir, mozarella pendiri, acı bibər", "/menu/mamajan/xemir-yemekleri/12.avif"],
    ["Xaçapuri Kubdari", 17, "Xaçapuri xəmiri, qovrulmuş ət qiyməsi, kərə yağı", "/menu/mamajan/xemir-yemekleri/13.avif"],
    ["Karolevski Xaçapuri", 19, "Xaçapuri xəmiri, ağ pendir, suluquni pendiri, mozarella pendiri, kərə yağı", "/menu/mamajan/xemir-yemekleri/14.avif"],
    ["Papajan & Mamajan", 19, "Xaçapuri xəmiri, qızardılmış gürcü xəngəli, ağ pendir, mozarella pendiri", "/menu/mamajan/xemir-yemekleri/15.avif"],
    ["Gürcüsayağı Pizza", 15, "Xaçapuri xəmiri, mozarella pendiri, pomidor, zeytun, toyuq filesi, göbələk", "/menu/mamajan/xemir-yemekleri/16.avif"],
    ["Çörək", 2.5, "Un, yaş maya, günəbaxan yağı", "/menu/mamajan/xemir-yemekleri/17.avif"],
    ["Pizza Margarita", 11, "Pizza xəmiri, mozarella pendiri, tomat sousu", "/menu/mamajan/xemir-yemekleri/18.avif"],
  ]),
  cat("Souslar", "food", [
    ["Qırmızı Tkemali", 2, undefined, "/menu/mamajan/souslar/0.avif"],
    ["Yaşıl Tkemali", 2, undefined, "/menu/mamajan/souslar/1.avif"],
    ["Acika", 2, undefined, "/menu/mamajan/souslar/2.avif"],
    ["Qatığ", 2, undefined, "/menu/mamajan/souslar/3.avif"],
    ["Ketçup", 1.5, undefined, "/menu/mamajan/souslar/4.avif"],
    ["Mayonez", 1.5, undefined, "/menu/mamajan/souslar/5.avif"],
  ]),
  cat("Desertlər", "food", [
    ["Meyvə (kiçik)", 20, undefined, "/menu/mamajan/desertler/0.avif"],
    ["Meyvə (böyük)", 25, undefined, "/menu/mamajan/desertler/1.avif"],
    ["Mürəbbə Çiyələk", 6, undefined, "/menu/mamajan/desertler/2.jpg"],
    ["Ləbləbi", 7, undefined, "/menu/mamajan/desertler/3.avif"],
    ["Çizkeyk", 7, undefined, "/menu/mamajan/desertler/4.jpg"],
    ["Ballı Tort", 7],
    ["Mürəbbə Ağ Gilas", 6, undefined, "/menu/mamajan/desertler/6.jpg"],
    ["Mürəbbə Moruq", 6, undefined, "/menu/mamajan/desertler/7.avif"],
    ["Südlü Paxlava", 8, undefined, "/menu/mamajan/desertler/8.jpg"],
    ["Türk Paxlavası", 8, undefined, "/menu/mamajan/desertler/9.jpg"],
    ["Ekler", 4],
    ["Çurçuxella", 8, undefined, "/menu/mamajan/desertler/11.avif"],
    ["Xaçapuri Qozlu", 10, undefined, "/menu/mamajan/desertler/12.jpg"],
  ]),

  // --- Bar & drinks ---
  cat("Sərin İçkilər", "bar", [
    ["Nataktari Limonad", 3.5, undefined, "/menu/mamajan/serin-i-ckiler/0.jpg"],
    ["Badamlı Qazlı", 4, undefined, "/menu/mamajan/serin-i-ckiler/1.jpg"],
    ["Badamlı Qazsız", 3, undefined, "/menu/mamajan/serin-i-ckiler/2.jpg"],
    ["Barjomi", 4, undefined, "/menu/mamajan/serin-i-ckiler/3.jpg"],
    ["Cola", 3, undefined, "/menu/mamajan/serin-i-ckiler/4.jpg"],
    ["Cola Zero", 3, undefined, "/menu/mamajan/serin-i-ckiler/5.jpg"],
    ["Fanta", 4, undefined, "/menu/mamajan/serin-i-ckiler/6.avif"],
    ["Sprite", 4, undefined, "/menu/mamajan/serin-i-ckiler/7.jpg"],
    ["Evsayağı Limonad 0.2 Lt", 6, undefined, "/menu/mamajan/serin-i-ckiler/8.jpg"],
    ["İce Tea Evsayağı", 5, undefined, "/menu/mamajan/serin-i-ckiler/9.jpg"],
    ["Meyvə Şirəsi", 4, undefined, "/menu/mamajan/serin-i-ckiler/10.avif"],
    ["Portağal Freş", 8, undefined, "/menu/mamajan/serin-i-ckiler/11.jpg"],
    ["Qarışıq Freş", 10, undefined, "/menu/mamajan/serin-i-ckiler/12.avif"],
    ["Kompot 1 Lt", 6, undefined, "/menu/mamajan/serin-i-ckiler/13.jpg"],
    ["Redbull", 6, undefined, "/menu/mamajan/serin-i-ckiler/14.jpg"],
    ["Alma Freş", 8, undefined, "/menu/mamajan/serin-i-ckiler/15.avif"],
    ["Zedazeni Limonad Düşes", 3.5, undefined, "/menu/mamajan/serin-i-ckiler/16.jpg"],
    ["Zedazeni Limonad Tərxun", 3.5, undefined, "/menu/mamajan/serin-i-ckiler/17.jpg"],
    ["Zedazeni Limonad Üzüm", 3.5, undefined, "/menu/mamajan/serin-i-ckiler/18.jpg"],
    ["Zedazeni Limonad Qaymaqlı", 3.5, undefined, "/menu/mamajan/serin-i-ckiler/19.jpg"],
    ["Evsayağı Limonad 1 Lt", 14, undefined, "/menu/mamajan/serin-i-ckiler/20.jpg"],
    ["Kobi Qazlı", 4, undefined, "/menu/mamajan/serin-i-ckiler/21.jpg"],
    ["Kobi Qazsız", 3],
    ["Təbii Nar Şirəsi", 5, undefined, "/menu/mamajan/serin-i-ckiler/23.jpg"],
    ["Sairme Qazlı", 4, undefined, "/menu/mamajan/serin-i-ckiler/24.jpg"],
    ["Sairme Qazsız", 3, undefined, "/menu/mamajan/serin-i-ckiler/25.jpg"],
    ["Sirab Qazlı", 4, undefined, "/menu/mamajan/serin-i-ckiler/26.jpg"],
    ["Sirab Qazsız", 3, undefined, "/menu/mamajan/serin-i-ckiler/27.jpg"],
    ["İce Tea", 4, undefined, "/menu/mamajan/serin-i-ckiler/28.jpg"],
    ["Ayran", 3, undefined, "/menu/mamajan/serin-i-ckiler/29.avif"],
    ["Təbii Nar Şirəsi 1 Lt", 12, undefined, "/menu/mamajan/serin-i-ckiler/30.jpg"],
    ["Meyvə Şirəsi 1 Lt", 9, undefined, "/menu/mamajan/serin-i-ckiler/31.avif"],
  ]),
  cat("İsti İçkilər", "bar", [
    ["Çay Dəstgahı", 25, "Badam, qovrulmuş fındıq, qoz, kişmiş, qovrulmuş fıstıq, meyvə qurusu, paxlava, mürəbbə, samovar çayı", "/menu/mamajan/i-sti-i-ckiler/0.avif"],
    ["Çay Çaynik", 5, undefined, "/menu/mamajan/i-sti-i-ckiler/1.avif"],
    ["Çay Fincan", 3, undefined, "/menu/mamajan/i-sti-i-ckiler/2.avif"],
    ["Jasmin Çayı", 7, undefined, "/menu/mamajan/i-sti-i-ckiler/3.avif"],
    ["Amerikano", 5, undefined, "/menu/mamajan/i-sti-i-ckiler/4.avif"],
    ["Yaşıl Çay", 6, undefined, "/menu/mamajan/i-sti-i-ckiler/5.avif"],
    ["Espresso", 5, undefined, "/menu/mamajan/i-sti-i-ckiler/6.avif"],
    ["Gürcü Qəhvəsi", 4, undefined, "/menu/mamajan/i-sti-i-ckiler/7.avif"],
  ]),
  cat("Ev Çaçaları", "bar", [
    ["Xüsusi Çaça (0.5 Lt)", 35],
    ["Xüsusi Çaça (50 Qr)", 5],
    ["Old Kaxeti Klassik (0.5 Lt)", 35],
    ["Old Kaxeti Klassik (50 Qr)", 5, undefined, "/menu/mamajan/ev-cacalari/3.jpg"],
    ["Old Kaxeti Palıd (0.5 Lt)", 35],
    ["Palıdlı Çaça (50 Qr)", 5, undefined, "/menu/mamajan/ev-cacalari/5.jpg"],
    ["Tərxunlu Çaça (0.5 Lt)", 35],
    ["Tərxunlu Çaça (50 Qr)", 5, undefined, "/menu/mamajan/ev-cacalari/7.jpg"],
    ["Ballı Çaça (0.5 Lt)", 35],
    ["Ballı Çaça (50 Qr)", 5, undefined, "/menu/mamajan/ev-cacalari/9.jpg"],
    ["Limonlu Çaça (0.5 Lt)", 35],
    ["Limonlu Çaça (50 Qr)", 5, undefined, "/menu/mamajan/ev-cacalari/11.jpg"],
  ]),
  cat("Pivələr", "bar", [
    ["Efes Draft", 5, undefined, "/menu/mamajan/piveler/0.jpg"],
    ["Efes Pilsener", 5, undefined, "/menu/mamajan/piveler/1.jpg"],
    ["Efes Zero", 4, undefined, "/menu/mamajan/piveler/2.jpg"],
    ["Miller", 7, undefined, "/menu/mamajan/piveler/3.jpg"],
    ["Heineken 0.5L", 7, undefined, "/menu/mamajan/piveler/4.jpg"],
    ["Xırdalan 0.5L", 4, undefined, "/menu/mamajan/piveler/5.jpg"],
    ["İcy Gürcü Pivəsi", 6, undefined, "/menu/mamajan/piveler/6.jpg"],
    ["Xırdalan N/F 0.5L", 5, undefined, "/menu/mamajan/piveler/7.jpg"],
    ["Kayaki Gürcü Pivəsi", 6, undefined, "/menu/mamajan/piveler/8.jpg"],
    ["Corona", 7, undefined, "/menu/mamajan/piveler/9.jpg"],
    ["Kazbegi Gürcü Pivəsi", 6, undefined, "/menu/mamajan/piveler/10.jpg"],
    ["Heineken 0.33L", 6, undefined, "/menu/mamajan/piveler/11.jpg"],
  ]),
  cat("Çəllək Pivəsi", "bar", [
    ["Xırdalan N/F (Çəllək) 0.33 Lt", 3.5, undefined, "/menu/mamajan/cellek-pivesi/0.avif"],
    ["Xırdalan Filtrsiz (Çəllək) 0.50 Lt", 5, undefined, "/menu/mamajan/cellek-pivesi/1.avif"],
    ["Xırdalan (Çəllək) 0.33 Lt", 3, undefined, "/menu/mamajan/cellek-pivesi/2.avif"],
    ["Xırdalan (Çəllək) 0.50 Lt", 5, undefined, "/menu/mamajan/cellek-pivesi/3.avif"],
  ]),
  cat("Ev Şərabları", "bar", [
    ["Saperavi 1 Lt", 35, undefined, "/menu/mamajan/ev-serablari/0.jpg"],
    ["Saperavi 0.2 Lt", 8, undefined, "/menu/mamajan/ev-serablari/1.jpg"],
    ["Rkatsiteli 1 Lt", 35, undefined, "/menu/mamajan/ev-serablari/2.jpg"],
    ["Rkatsiteli 0.2 Lt", 8, undefined, "/menu/mamajan/ev-serablari/3.jpg"],
    ["Kindsmarauli 1 Lt", 35],
    ["Kindsmarauli 0.2 Lt", 7],
  ]),
  cat("Şərablar", "bar", [
    ["Marani Kindzmarauli 0.75 Lt", 30, undefined, "/menu/mamajan/serablar/0.jpg"],
    ["Marani Rkatsiteli 0.75 Lt", 30, undefined, "/menu/mamajan/serablar/1.jpg"],
    ["Marani Saperavi 0.75 Lt", 30, undefined, "/menu/mamajan/serablar/2.jpg"],
    ["Marani Tsinandali 0.75 Lt", 30, undefined, "/menu/mamajan/serablar/3.jpg"],
    ["İveriya Tsinandali 0.75 Lt", 28, undefined, "/menu/mamajan/serablar/4.jpg"],
    ["İveriya Tvishi 0.75 Lt", 28, undefined, "/menu/mamajan/serablar/5.jpg"],
    ["İveriya Saperavi 0.75 Lt", 28, undefined, "/menu/mamajan/serablar/6.jpg"],
    ["İveriya Kindsmarauli 0.75 Lt", 28, undefined, "/menu/mamajan/serablar/7.jpg"],
    ["İveriya Xvançkara 0.75 Lt", 28, undefined, "/menu/mamajan/serablar/8.jpg"],
    ["Marani Xvançkara 0.75 Lt", 30, undefined, "/menu/mamajan/serablar/9.jpg"],
    ["Dugladze Rose 0.75 Lt", 30, undefined, "/menu/mamajan/serablar/10.jpg"],
    ["Dugladze Mukuzani 5 Lt", 300],
    ["Dugladze Mukuzani 3 Lt", 200],
  ]),
  cat("Pivə Qəlyanaltıları", "bar", [
    ["Saçaqlı Pendir", 5, "150 qram", "/menu/mamajan/pive-qelyanaltilari/0.webp"],
    ["Chips", 6, "100 qram", "/menu/mamajan/pive-qelyanaltilari/1.webp"],
    ["Qovrulmuş Püstə", 7, "200 qram", "/menu/mamajan/pive-qelyanaltilari/2.avif"],
    ["Qızardılmış Düşbərə", 6, "200 qram", "/menu/mamajan/pive-qelyanaltilari/3.webp"],
    ["Çipsi", 4, "Kartof, günəbaxan yağı", "/menu/mamajan/pive-qelyanaltilari/4.avif"],
  ]),
  cat("Araq", "bar", [
    ["Stumbras 0.7 Lt", 55, undefined, "/menu/mamajan/araq/0.avif"],
    ["Stumbras 0.5 Lt", 45, undefined, "/menu/mamajan/araq/1.avif"],
    ["Stumbras 50 Qr", 5, undefined, "/menu/mamajan/araq/2.avif"],
    ["Minsk 0.7 Lt", 39, undefined, "/menu/mamajan/araq/3.avif"],
    ["Minsk 0.5 Lt", 29, undefined, "/menu/mamajan/araq/4.avif"],
    ["Onegin 0.7 Lt", 80, undefined, "/menu/mamajan/araq/5.jpg"],
    ["Onegin 0.5 Lt", 65, undefined, "/menu/mamajan/araq/6.jpg"],
    ["ZernO 0.7 Lt", 40, undefined, "/menu/mamajan/araq/7.jpg"],
    ["ZernO 0.5 Lt", 35, undefined, "/menu/mamajan/araq/8.jpg"],
    ["Kirke Gürcü 0.7 Lt", 45, undefined, "/menu/mamajan/araq/9.jpg"],
    ["Kirke Gürcü 0.5 Lt", 35, undefined, "/menu/mamajan/araq/10.jpg"],
    ["Nemiroff Delikat 0.7 Lt", 50, undefined, "/menu/mamajan/araq/11.avif"],
    ["Nemiroff Delikat 0.5 Lt", 40, undefined, "/menu/mamajan/araq/12.avif"],
    ["Nemiroff Delikat 50 Qr", 5, undefined, "/menu/mamajan/araq/13.avif"],
    ["Zerna Severa 0.7 Lt", 80, undefined, "/menu/mamajan/araq/14.avif"],
    ["Zerna Severa 0.5 Lt", 60, undefined, "/menu/mamajan/araq/15.avif"],
    ["Louvre 0.7 Lt", 60, undefined, "/menu/mamajan/araq/16.avif"],
    ["Louvre 0.5 Lt", 50, undefined, "/menu/mamajan/araq/17.avif"],
    ["Belaya Loşad 0.7 Lt", 45, undefined, "/menu/mamajan/araq/18.jpg"],
    ["Belaya Loşad 0.5 Lt", 35, undefined, "/menu/mamajan/araq/19.jpg"],
  ]),
  cat("Tekila", "bar", [
    ["Olmeca Silver 0.7 Lt", 75, undefined, "/menu/mamajan/tekila/0.avif"],
    ["Olmeca Silver 50 Qr", 6],
    ["Olmeca Gold 0.7 Lt", 85, undefined, "/menu/mamajan/tekila/2.avif"],
    ["Olmeca Gold 50 Qr", 6],
    ["Patron 0.7 Lt", 130, undefined, "/menu/mamajan/tekila/4.avif"],
  ]),
  cat("Viski", "bar", [
    ["Chivas 12 0.7 Lt", 90, undefined, "/menu/mamajan/viski/0.avif"],
    ["Chivas 12 0.5 Lt", 70, undefined, "/menu/mamajan/viski/1.avif"],
    ["Chivas 12 50 Qr", 8, undefined, "/menu/mamajan/viski/2.avif"],
    ["Chivas 18 0.7 Lt", 150, undefined, "/menu/mamajan/viski/3.avif"],
    ["Chivas 18 0.5 Lt", 110, undefined, "/menu/mamajan/viski/4.avif"],
    ["Chivas 18 50 Qr", 15, undefined, "/menu/mamajan/viski/5.avif"],
    ["Jameson 0.7 Lt", 70, undefined, "/menu/mamajan/viski/6.avif"],
    ["Jameson 50 Qr", 6, undefined, "/menu/mamajan/viski/7.avif"],
    ["Jack Daniel's 0.7 Lt", 75, undefined, "/menu/mamajan/viski/8.avif"],
    ["Jack Daniel's 50 Qr", 6, undefined, "/menu/mamajan/viski/9.avif"],
    ["Monkey Shoulders 0.7 Lt", 95, undefined, "/menu/mamajan/viski/10.avif"],
    ["Monkey Shoulders 50 Qr", 9, undefined, "/menu/mamajan/viski/11.avif"],
  ]),
  cat("Cin", "bar", [
    ["Gordons 0.7 Lt", 80, undefined, "/menu/mamajan/cin/0.avif"],
    ["Gordons 50 Qr", 6, undefined, "/menu/mamajan/cin/1.avif"],
    ["Hendrick's 0.7 Lt", 80, undefined, "/menu/mamajan/cin/2.avif"],
    ["Hendrick's 50 Qr", 10, undefined, "/menu/mamajan/cin/3.avif"],
  ]),
  cat("Aperativ", "bar", [
    ["Jagermeister 0.7 Lt", 70, undefined, "/menu/mamajan/aperativ/0.avif"],
    ["Jagermeister 50 Qr", 6, undefined, "/menu/mamajan/aperativ/1.avif"],
    ["Aperol 0.7 Lt", 70, undefined, "/menu/mamajan/aperativ/2.avif"],
    ["Aperol 50 Qr", 5, undefined, "/menu/mamajan/aperativ/3.avif"],
    ["Campari 0.7 Lt", 70, undefined, "/menu/mamajan/aperativ/4.avif"],
    ["Campari 50 Qr", 5, undefined, "/menu/mamajan/aperativ/5.avif"],
  ]),
  cat("Şampan / Prosecco", "bar", [
    ["Martini Asti 0.75 Lt", 60, undefined, "/menu/mamajan/sampan-prosecco/0.avif"],
    ["Montresor Prosecco 0.75 Lt", 60, undefined, "/menu/mamajan/sampan-prosecco/1.avif"],
  ]),
  cat("Konyak", "bar", [
    ["Sarajashvili V.S 0.7 Lt", 70, undefined, "/menu/mamajan/konyak/0.jpg"],
    ["Sarajashvili V.S 50 Qr", 6, undefined, "/menu/mamajan/konyak/1.jpg"],
    ["Sarajashvili V.S.O.P 0.7 Lt", 130, undefined, "/menu/mamajan/konyak/2.jpg"],
    ["Sarajashvili V.S.O.P 50 Qr", 10, undefined, "/menu/mamajan/konyak/3.jpg"],
    ["Sarajashvili X.O 0.7 Lt", 190, undefined, "/menu/mamajan/konyak/4.jpg"],
    ["Sarajashvili X.O 50 Qr", 15, undefined, "/menu/mamajan/konyak/5.jpg"],
    ["Tikhari 0.5 Lt", 40, undefined, "/menu/mamajan/konyak/6.jpg"],
    ["Tikhari 50 Ml", 6, undefined, "/menu/mamajan/konyak/7.jpg"],
  ]),
  cat("Vermouth", "bar", [
    ["Martini Bianco 0.75 Lt", 60, undefined, "/menu/mamajan/vermouth/0.avif"],
    ["Martini Bianco 50 Qr", 6, undefined, "/menu/mamajan/vermouth/1.avif"],
    ["Martini Rosso 0.75 Lt", 60, undefined, "/menu/mamajan/vermouth/2.avif"],
    ["Martini Rosso 50 Qr", 6, undefined, "/menu/mamajan/vermouth/3.avif"],
  ]),
  cat("Rum", "bar", [
    ["Bacardi 1 Lt", 90, undefined, "/menu/mamajan/rum/0.avif"],
    ["Bacardi 50 Qr", 6, undefined, "/menu/mamajan/rum/1.avif"],
    ["Captain Morgan 1 Lt", 90, undefined, "/menu/mamajan/rum/2.avif"],
    ["Captain Morgan 50 Qr", 6, undefined, "/menu/mamajan/rum/3.avif"],
  ]),
  cat("Liquor", "bar", [
    ["Bailays 1 Lt", 140, undefined, "/menu/mamajan/liquor/0.avif"],
    ["Bailays 50 Qr", 8, undefined, "/menu/mamajan/liquor/1.avif"],
    ["Absente 1 Lt", 120, undefined, "/menu/mamajan/liquor/2.jpg"],
    ["Absente 50 Qr", 7, undefined, "/menu/mamajan/liquor/3.avif"],
  ]),
  cat("Rakı", "bar", [
    ["Yeni Rakı 0.7 Lt", 90, undefined, "/menu/mamajan/raki/0.avif"],
    ["Yeni Rakı 0.5 Lt", 70, undefined, "/menu/mamajan/raki/1.avif"],
    ["Yeni Rakı 50 Qr", 6, undefined, "/menu/mamajan/raki/2.avif"],
    ["Tekirdağ 0.7 Lt", 110, undefined, "/menu/mamajan/raki/3.avif"],
    ["Tekirdağ 0.35 Lt", 50, undefined, "/menu/mamajan/raki/4.avif"],
  ]),
  cat("Extra Qida", "bar", [
    ["Limon", 2, undefined, "/menu/mamajan/extra-qida/0.avif"],
    ["Yarpaq Xəngəl", 12, undefined, "/menu/mamajan/extra-qida/1.jpg"],
    ["Ağ Pendir", 5, undefined, "/menu/mamajan/extra-qida/2.jpg"],
    ["Yaşıl Alma", 5, undefined, "/menu/mamajan/extra-qida/3.jpg"],
    ["Portağal", 5, undefined, "/menu/mamajan/extra-qida/4.jpg"],
    ["Kələm Turşusu", 4, undefined, "/menu/mamajan/extra-qida/5.jpg"],
    ["Xiyar Turşusu", 4, undefined, "/menu/mamajan/extra-qida/6.jpg"],
    ["Alça Turşusu", 5, undefined, "/menu/mamajan/extra-qida/7.jpg"],
    ["Acı Bibər", 4, undefined, "/menu/mamajan/extra-qida/8.jpg"],
    ["Bibər Turşusu", 4, undefined, "/menu/mamajan/extra-qida/9.jpg"],
    ["Pomidor Yumurta", 6, undefined, "/menu/mamajan/extra-qida/10.jpg"],
    ["Lavaş", 2, undefined, "/menu/mamajan/extra-qida/11.jpg"],
  ]),
  cat("Alkoqolsuz Kokteyllər", "bar", [
    ["Virgin Moxito", 7, undefined, "/menu/mamajan/alkoqolsuz-kokteyller/0.avif"],
    ["Tropical İcland", 8, undefined, "/menu/mamajan/alkoqolsuz-kokteyller/1.avif"],
    ["Barbados", 10, undefined, "/menu/mamajan/alkoqolsuz-kokteyller/2.avif"],
    ["Milkshake", 8, undefined, "/menu/mamajan/alkoqolsuz-kokteyller/3.avif"],
    ["Summer Sunset", 10, undefined, "/menu/mamajan/alkoqolsuz-kokteyller/4.avif"],
    ["Sindirella", 9, undefined, "/menu/mamajan/alkoqolsuz-kokteyller/5.avif"],
    ["Sangria (Alkoqolsuz)", 10, undefined, "/menu/mamajan/alkoqolsuz-kokteyller/6.avif"],
  ]),
  cat("Alkoqollu Kokteyllər", "bar", [
    ["Pina Colada", 12, undefined, "/menu/mamajan/alkoqollu-kokteyller/0.avif"],
    ["Aperol Spritz", 12, undefined, "/menu/mamajan/alkoqollu-kokteyller/1.avif"],
    ["Long İceland", 15, undefined, "/menu/mamajan/alkoqollu-kokteyller/2.avif"],
    ["Margarita", 12, undefined, "/menu/mamajan/alkoqollu-kokteyller/3.avif"],
    ["Jin Tonic", 12, undefined, "/menu/mamajan/alkoqollu-kokteyller/4.avif"],
    ["Sex On The Beach", 13, undefined, "/menu/mamajan/alkoqollu-kokteyller/5.avif"],
    ["Mamajan", 15, undefined, "/menu/mamajan/alkoqollu-kokteyller/6.avif"],
    ["Negroni", 13, undefined, "/menu/mamajan/alkoqollu-kokteyller/7.avif"],
    ["Cosmopolitan", 11, undefined, "/menu/mamajan/alkoqollu-kokteyller/8.avif"],
    ["Papajan Eksklusiv", 15, undefined, "/menu/mamajan/alkoqollu-kokteyller/9.avif"],
    ["Banana Drama", 15, undefined, "/menu/mamajan/alkoqollu-kokteyller/10.avif"],
    ["Moxito Alcohol", 12, undefined, "/menu/mamajan/alkoqollu-kokteyller/11.avif"],
  ]),
  cat("Shot (6 Ədəd)", "bar", [
    ["Alabama", 15, undefined, "/menu/mamajan/shot-6-eded/0.avif"],
    ["Kamikadze", 15, undefined, "/menu/mamajan/shot-6-eded/1.avif"],
    ["Rainbow", 11, undefined, "/menu/mamajan/shot-6-eded/2.avif"],
    ["Sun Rice", 18, undefined, "/menu/mamajan/shot-6-eded/3.avif"],
  ]),
]

export const mamajanMenuItemCount = mamajanMenu.reduce((n, c) => n + c.items.length, 0)
